version: '3.1'

services:
 py_client_gp:
    build: './05-client-py'
    container_name: client05-py
    restart: always
    volumes:
      - "./05-client-py/src:/src"
    depends_on:
      -  py_server_gp
    ports:
      - "8085:80"

 py_server_gp:
    build: './04-server-py'
    container_name: server04-py
    restart: always
    volumes:
      - "./04-server-py/src:/src"
    depends_on:
      -  mysql_server_gp
    ports:
      - "50004:5000"
      - "8084:80"

 c_client_gp:
    build: './03-client-c'
    container_name: client03-c
    restart: always
    volumes:
      - "./03-client-c/src:/src"
    depends_on:
      -  c_server_gp
    ports:
      - "8083:80"

 c_server_gp:
    build: './02-server-c'
    container_name: server02-c
    restart: always
    volumes:
      - "./02-server-c/src:/src"
    depends_on:
      -  mysql_server_gp
    ports:
      - "50002:5000"
      - "8082:80"

 mysql_server_gp:
    build: './01-mysql'
    container_name: server01-mysql
    restart: always
    volumes:
      - "./01-mysql/src/gp_db.sql:/docker-entrypoint-initdb.d/init_1.sql"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "30000:3306